runtime: php74

runtime_config:
  document_root: public

env_variables:
  ## Set these environment variables according to your CloudSQL con
  ## DATABASE_URL: mysql://root:test123@35.192.167.103?unix_socket=/cloudsql/symfony-deployment-353414:us-central1:symfony-deployment-sql;dbname=mysql
  DB_DATABASE: mysql
  DB_HOST: '35.192.167.103'
  DB_PORT: 3306
  DB_USERNAME: root
  DB_PASSWORD: tRfg34K=Tjl;=kdH
  DB_SOCKET: "/cloudsql/symfony-deployment-353414:us-central1:symfony-deployment-sql"

beta_settings:
  # for Cloud SQL, set this value to the Cloud SQL connection name,
  # e.g. "project:region:cloudsql-instance"
  cloud_sql_instances: "symfony-deployment-353414:us-central1:symfony-deployment-sql"