runtime: php74

runtime_config:
  document_root: public

env_variables:
  ## Set these environment variables according to your CloudSQL con
  DATABASE_URL: mysql://root:tRfg34K=Tjl;=kdH@35.192.167.103?unix_socket=/cloudsql/symfony-deployment-353414:us-central1:symfony-deployment-sql;dbname=mysql